version: '3.8'

services:
  postgres_db:
    image: postgres:13
    container_name: mlflow_postgres
    restart: always
    environment:
      POSTGRES_USER: mlflow_user
      POSTGRES_PASSWORD: mlflow_password
      POSTGRES_DB: mlflow_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:z

  mlflow_server:
    build: ./mlflow
    container_name: mlflow_server
    restart: always
    depends_on:
      - postgres_db
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri postgresql://mlflow_user:mlflow_password@postgres_db:5432/mlflow_db
      --artifacts-destination /mlflow/artifacts
      --serve-artifacts